keymap:
  - name: Global
    remap:
      # Alt-SEMICOLON: { launch: ["xdotool", "type", "ö"] }
      M-SEMICOLON: { launch: ["xdotool", "type", "ö"] }
      M-APOSTROPHE: { launch: ["xdotool", "type", "ä"] }
      backslash: { launch: ["xdotool", "type", "ü"] }
      # Alt-SEMICOLON: { to: U00F6 }

# KEY_SEMICOLON
# KEY_APOSTROPHE
# KEY_BACKSLASH
# KEY_EQUAL
# KEY_MINUS
modmap:
  - name: Global
    remap:
      # CapsLock/Ctrl_L -> Esc
      # CapsLock: Ctrl_L
      # Ctrl_L: Esc
      # M-;: [U00F6]
      # semicolon: { to: ö }
      # semicolon: { to: U00F6 }
      # KEY_SEMICOLON: { launch: ["xdotool", "type", "ö"] }
      # M-': { to: ä }
      # M-\\: { to: ü }
      # M-S-;: { to: Ö }
      # M-S-': { to: Ä }
      # M-S-\\: { to: Ü }
      # M--: { to: ß }
      #

      # HHKB: [Alt_L] [Muhenkan] [Space] [Henkan] [KatakanaHiragana]
      # Alt_L: Ctrl_R # for Ctrl+Click
      # Muhenkan: Ctrl_L
      # Henkan: Shift_L

  # - name: Kana -> Windows
  #   application:
  #     not: jetbrains-idea
  #   remap:
  #     # Use Windows since Alt is annoying in Electron apps (Slack, Nocturn)
  #     KatakanaHiragana: Win_R
  #
  # - name: Kana -> Alt
  #   application:
  #     only: jetbrains-idea
  #   remap:
  #     # Use Alt since Windows is annoying in IDEA
  #     KatakanaHiragana: Alt_L
