#!bash
gsettings set org.gnome.desktop.interface color-scheme  'prefer-dark'

cp $HOME/.config/kitty/darkmode.conf $HOME/.config/kitty/kitty.conf
TO_FILE=$HOME/.config/kitty/kitty.conf
sed -i '1i\# Generated by dotfiles/scripts/mode-dark.sh' $TO_FILE
kill -SIGUSR1 $(pidof kitty)
# sleep 2
kill -SIGUSR1 $(pidof nvim)

# sed on .bak because otherwise k9s' reactive system doesn't pick up the file change
K9S=$HOME/.config/k9s/config.yaml
cp $K9S $K9S.bak
sed -i 's/skin:.*$/skin: dracula/' $K9S.bak
cp $K9S.bak $K9S
