hotKeys:

  # Hitting Shift-0 navigates to your pod view matching pods with labels app=kindnet
  Durr:
    shortCut:    Shift-1
    description: Viewing pods
    command:     pods
    # command:     pods app=apisix

  P:
    shortCut:    Ctrl-1
    description: Viewing pods
    command:     pods

  ApisixRoutes:
    shortCut:    Shift-2
    description: View Services
    command:     svc

  shift-3:
    shortCut:    Shift-3
    description: View deployments
    command:     apisixroutes

  shift-4:
    shortCut:    Shift-4
    description: ManifestWorks
    command:     ManifestWorks

  shift-5:
    shortCut:    Shift-5
    description: Sensors
    command:     Sensors

