hotKeys:

  # Hitting Shift-0 navigates to your pod view matching pods with labels app=kindnet
  Durr:
    shortCut:    Shift-1
    description: Viewing pods
    command:     pods
    # command:     pods app=apisix

  # Hitting Shift-1 navigates to your deployments
  ApisixRoutes:
    shortCut:    Shift-2
    description: View deployments
    command:     apisixroutes

  shift-3:
    shortCut:    Shift-3
    description: View Services
    command:     svc

  # Hitting Shift-2 navigates to your xray deployments
  shift-4:
    shortCut:    Shift-4
    description: XRay pods
    command:     xray pods
